#!/bin/sh

# User specific environment and startup programs
export PATH=$HOME/bin:/usr/local/bin:$PATH

# History with date and ignore space
export HISTTIMEFORMAT="%d/%m/%y %T "
export HISTCONTROL=ignorespace:ignoredups
#export HISTORYIGNORE="cd:ls:su"

# Text editors
export VISUAL=/usr/bin/nvim
export EDITOR=/usr/bin/nvim
export PAGER="less --quit-if-one-screen --RAW-CONTROL-CHARS --LINE-NUMBERS --LONG-PROMPT"

# Terminals
export TERM=xterm-256color
export TERMINAL="st"

# Applications
#export BROWSER="surf -u 'Mozilla/5.0 (Windows NT 10.0;) Gecko Firefox/66.0' -dgNpis -a a"
export READER="mupdf"
export FILE="ranger"

# GTK2 cutomized
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"

# less/man colors
export LESS="--RAW-CONTROL-CHARS"
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"; a="${a%_}"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"; a="${a%_}"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"; a="${a%_}"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"; a="${a%_}"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"; a="${a%_}"
export MANPAGER="less --squeeze-blank-lines --LONG-PROMPT +Gg"

# XDG standards
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
