codium --install-extension aaron-bond.better-comments
codium --install-extension amandeepmittal.expressjs
codium --install-extension capaj.vscode-standardjs-snippets
codium --install-extension chenxsan.vscode-standardjs
codium --install-extension christian-kohler.npm-intellisense
codium --install-extension christian-kohler.path-intellisense
codium --install-extension digitalbrainstem.javascript-ejs-support
codium --install-extension eg2.vscode-npm-script
codium --install-extension formulahendry.auto-rename-tag
codium --install-extension hookyqr.beautify
codium --install-extension redhat.vscode-yaml
codium --install-extension tyriar.sort-lines
codium --install-extension visualstudioexptteam.vscodeintellicode
codium --install-extension vscode-icons-team.vscode-icons
codium --install-extension vscoss.vscode-ansible
codium --install-extension xabikos.javascriptsnippets
codium --install-extension msjsdiag.vscode-react-native
codium --install-extension chakrounanas.turbo-console-log
codium --install-extension coenraads.bracket-pair-colorizer