#!/usr/bin/sh

# autostart
sxhkd &
feh --bg-center ~/Images/wallpaper.png &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 &
urxvt -e ranger &
sleep 5s && bspc desktop -f '^2' && urxvt -e newsboat &
chromium-browser --password-store=basic --incognito https://franckf.gitlab.io/startpage/ &
unclutter -idle 5 &
light -U 90 &

# multi-monitor
bspc monitor eDP      -d 1 2 3 4 5 6 7
bspc monitor HDMI-A-0 -d 8 9 10

# borders style
bspc config border_width         2
bspc config window_gap           0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# mouse and windows
bspc config pointer_modifier     mod4
bspc config pointer_action1      move
bspc config pointer_action2      resize_side

# assign program to desktop
bspc rule -a Chromium-browser    desktop='^3'
