#!/usr/bin/sh

# autostart
# keybinding
sxhkd &
# wallpaper
feh --bg-center ~/.config/themes/wallpaper.png &
# low brightness
light -U 90 &
# clone monitor
xrandr --output HDMI-A-0 --same-as eDP --mode 1920x1080 &
# touchpad
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 &
# hide cursor
unclutter -idle 5 &
# fix cursor
xsetroot -cursor_name left_ptr &
# weather
sleep 5s && curl -s http://wttr.in/poitiers?format=%C+%t+%p+%w+%m > ~/.weather
# programs
# 1 file manager
urxvt -e ranger &
# 2 rss feed
sleep 5s && bspc desktop -f '^2' && urxvt -e newsboat &
# 3 web browser
chromium-browser --password-store=basic --incognito https://franckf.gitlab.io/startpage/ &

# multi-monitor
bspc monitor eDP      -d 1 2 3 4 5 6 7 8 9 10

# borders style
bspc config border_width         0
bspc config window_gap           0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# mouse and windows
bspc config pointer_modifier     mod4
bspc config pointer_action1      move
bspc config pointer_action2      resize_side

# assign program to desktop
bspc rule -a Chromium-browser    desktop='^3'
